services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "0.0.0.0:6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/_data

volumes:
  postgres_data:
