site_name: Bike Supply Chain
docs_dir: user-docs/docs

theme:
  name: material
  language: de
  logo: images/icon_512.png
  favicon: images/favicon_32_new.png
  palette:
    scheme: slate
    primary: deep purple
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - mermaid
    - navigation.tabs
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - content.code.copy
    - content.code.mermaid
    - content.footnote.tooltips
    - content.tooltips

nav:
  - Start: index.md
  - Einführung: simulation-information.md
  - Berechnung:
      - Material Planung: calculations/material-planning.md
      - Materialkosten: calculations/material-costs.md
      - Lagerkosten: calculations/storage_cost_analysis.md
      - Arbeitsstationen: calculations/workplaces.md
      - Arbeitskosten: calculations/labour-costs.md
      - Produktions Planung: calculations/workstation_plan.md
  - Optimierung: optimization.md
  - Python: python-implementation.md
  - PDF: pdf.md
markdown_extensions:
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - markdown_include.include:
      base_path: docs
  - attr_list
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - def_list
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - user-docs/includes

extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css
