[project]
name = "ibsys2scm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.4.2",
    "notebook>=7.3.2",
    "pandas>=2.2.3",
]
