[project]
name = "ibsys2scm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pybase62>=1.0.0",
    "pytest>=8.3.5",
    "pyyaml>=6.0.2",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.39",
    "sqlmodel>=0.0.24",
]
