[project]
name = "ibsys2scm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.4.2",
    "pytest>=8.3.5",
    "pyyaml>=6.0.2",
]
