%%{
  init: {
    'theme': 'dark'
  },
  'themeVariables': {
    'darkMode': true
  }
}%%
flowchart LR
    15.A["<div style='font-size:18px'><b>15</b></div>3<br/>15"]
    6.B["<div style='font-size:18px'><b>6</b></div>2<br/>15"]
    14.B["<div style='font-size:18px'><b>14</b></div>3<br/>0"]
    13.C["<div style='font-size:18px'><b>13</b></div>2<br/>0"]
    12.C["<div style='font-size:18px'><b>12</b></div>3<br/>0"]
    8.C["<div style='font-size:18px'><b>8</b></div>1<br/>15"]
    7.C["<div style='font-size:18px'><b>7</b></div>2<br/>20"]
    9.C["<div style='font-size:18px'><b>9</b></div>3<br/>15"]
    6.D["<div style='font-size:18px'><b>6</b></div>3<br/>15"]
    7.D["<div style='font-size:18px'><b>7</b></div>2<br/>20"]
    8.D["<div style='font-size:18px'><b>8</b></div>1<br/>15"]
    9.D["<div style='font-size:18px'><b>9</b></div>2<br/>20"]
    10.E["<div style='font-size:18px'><b>10</b></div>4<br/>20"]
    11.E["<div style='font-size:18px'><b>11</b></div>3<br/>20"]
    10.F["<div style='font-size:18px'><b>10</b></div>4<br/>20"]
    11.F["<div style='font-size:18px'><b>11</b></div>3<br/>10"]
    13.G["<div style='font-size:18px'><b>13</b></div>2<br/>0"]
    12.G["<div style='font-size:18px'><b>12</b></div>3<br/>0"]
    8.G["<div style='font-size:18px'><b>8</b></div>1<br/>15"]
    7.G["<div style='font-size:18px'><b>7</b></div>2<br/>20"]
    9.G["<div style='font-size:18px'><b>9</b></div>3<br/>15"]
    7.H["<div style='font-size:18px'><b>7</b></div>2<br/>30"]
    15.H["<div style='font-size:18px'><b>15</b></div>3<br/>15"]
    1.w["<div style='font-size:18px'><b>1</b></div>6<br/>20"]
    2.x["<div style='font-size:18px'><b>2</b></div>5<br/>30"]
    4.z["<div style='font-size:18px'><b>4</b></div>6<br/>30"]
    3.y["<div style='font-size:18px'><b>3</b></div>5<br/>20"]
    E2([<div style='font-size:10px'>E2</div>])
    15.A([<div style='font-size:10px'>15.A</div>])
    6.B([<div style='font-size:10px'>6.B</div>])
    14.B([<div style='font-size:10px'>14.B</div>])
    13.C([<div style='font-size:10px'>13.C</div>])
    12.C([<div style='font-size:10px'>12.C</div>])
    8.C([<div style='font-size:10px'>8.C</div>])
    7.C([<div style='font-size:10px'>7.C</div>])
    9.C([<div style='font-size:10px'>9.C</div>])
    6.D([<div style='font-size:10px'>6.D</div>])
    7.D([<div style='font-size:10px'>7.D</div>])
    8.D([<div style='font-size:10px'>8.D</div>])
    9.D([<div style='font-size:10px'>9.D</div>])
    10.E([<div style='font-size:10px'>10.E</div>])
    11.E([<div style='font-size:10px'>11.E</div>])
    10.F([<div style='font-size:10px'>10.F</div>])
    11.F([<div style='font-size:10px'>11.F</div>])
    13.G([<div style='font-size:10px'>13.G</div>])
    12.G([<div style='font-size:10px'>12.G</div>])
    8.G([<div style='font-size:10px'>8.G</div>])
    7.G([<div style='font-size:10px'>7.G</div>])
    9.G([<div style='font-size:10px'>9.G</div>])
    7.H([<div style='font-size:10px'>7.H</div>])
    15.H([<div style='font-size:10px'>15.H</div>])
    1.w([<div style='font-size:10px'>1.w</div>])
    2.x([<div style='font-size:10px'>2.x</div>])
    4.z([<div style='font-size:10px'>4.z</div>])
    3.y([<div style='font-size:10px'>3.y</div>])
    K43([<div style='font-size:10px'>K43</div>])
    K44([<div style='font-size:10px'>K44</div>])
    K45([<div style='font-size:10px'>K45</div>])
    K46([<div style='font-size:10px'>K46</div>])
    E17([<div style='font-size:10px'>E17</div>])
    K28([<div style='font-size:10px'>K28</div>])
    K24([<div style='font-size:10px'>K24</div>])
    K40([<div style='font-size:10px'>K40</div>])
    K41([<div style='font-size:10px'>K41</div>])
    K42([<div style='font-size:10px'>K42</div>])
    E16([<div style='font-size:10px'>E16</div>])
    K39([<div style='font-size:10px'>K39</div>])
    K32([<div style='font-size:10px'>K32</div>])
    E14([<div style='font-size:10px'>E14</div>])
    K59([<div style='font-size:10px'>K59</div>])
    E19([<div style='font-size:10px'>E19</div>])
    K57([<div style='font-size:10px'>K57</div>])
    K58([<div style='font-size:10px'>K58</div>])
    K35([<div style='font-size:10px'>K35</div>])
    K37([<div style='font-size:10px'>K37</div>])
    K38([<div style='font-size:10px'>K38</div>])
    E8([<div style='font-size:10px'>E8</div>])
    K36([<div style='font-size:10px'>K36</div>])
    E5([<div style='font-size:10px'>E5</div>])
    E11([<div style='font-size:10px'>E11</div>])
    K48([<div style='font-size:10px'>K48</div>])
    K47([<div style='font-size:10px'>K47</div>])
    E26([<div style='font-size:10px'>E26</div>])
    K25([<div style='font-size:10px'>K25</div>])
    K26([<div style='font-size:10px'>K26</div>])
    E54([<div style='font-size:10px'>E54</div>])
    E55([<div style='font-size:10px'>E55</div>])
    K27([<div style='font-size:10px'>K27</div>])
    E56([<div style='font-size:10px'>E56</div>])
    K22([<div style='font-size:10px'>K22</div>])
    subgraph A[<div style='font-size:21px'><b>A</b><br/></div>]
        15.A["<div style='font-size:18px'><b>15</b></div>3<br/>15"]
    end

    subgraph B[<div style='font-size:21px'><b>B</b><br/></div>]
        6.B["<div style='font-size:18px'><b>6</b></div>2<br/>15"]
        14.B["<div style='font-size:18px'><b>14</b></div>3<br/>0"]
    end

    subgraph C[<div style='font-size:21px'><b>C</b><br/></div>]
        13.C["<div style='font-size:18px'><b>13</b></div>2<br/>0"]
        12.C["<div style='font-size:18px'><b>12</b></div>3<br/>0"]
        8.C["<div style='font-size:18px'><b>8</b></div>1<br/>15"]
        7.C["<div style='font-size:18px'><b>7</b></div>2<br/>20"]
        9.C["<div style='font-size:18px'><b>9</b></div>3<br/>15"]
    end

    subgraph D[<div style='font-size:21px'><b>D</b><br/></div>]
        6.D["<div style='font-size:18px'><b>6</b></div>3<br/>15"]
        7.D["<div style='font-size:18px'><b>7</b></div>2<br/>20"]
        8.D["<div style='font-size:18px'><b>8</b></div>1<br/>15"]
        9.D["<div style='font-size:18px'><b>9</b></div>2<br/>20"]
    end

    subgraph E[<div style='font-size:21px'><b>E</b><br/></div>]
        10.E["<div style='font-size:18px'><b>10</b></div>4<br/>20"]
        11.E["<div style='font-size:18px'><b>11</b></div>3<br/>20"]
    end

    subgraph F[<div style='font-size:21px'><b>F</b><br/></div>]
        10.F["<div style='font-size:18px'><b>10</b></div>4<br/>20"]
        11.F["<div style='font-size:18px'><b>11</b></div>3<br/>10"]
    end

    subgraph G[<div style='font-size:21px'><b>G</b><br/></div>]
        13.G["<div style='font-size:18px'><b>13</b></div>2<br/>0"]
        12.G["<div style='font-size:18px'><b>12</b></div>3<br/>0"]
        8.G["<div style='font-size:18px'><b>8</b></div>1<br/>15"]
        7.G["<div style='font-size:18px'><b>7</b></div>2<br/>20"]
        9.G["<div style='font-size:18px'><b>9</b></div>3<br/>15"]
    end

    subgraph H[<div style='font-size:21px'><b>H</b><br/></div>]
        7.H["<div style='font-size:18px'><b>7</b></div>2<br/>30"]
        15.H["<div style='font-size:18px'><b>15</b></div>3<br/>15"]
    end

    subgraph w[<div style='font-size:21px'><b>w</b><br/></div>]
        1.w["<div style='font-size:18px'><b>1</b></div>6<br/>20"]
    end

    subgraph x[<div style='font-size:21px'><b>x</b><br/></div>]
        2.x["<div style='font-size:18px'><b>2</b></div>5<br/>30"]
    end

    subgraph y[<div style='font-size:21px'><b>y</b><br/></div>]
        3.y["<div style='font-size:18px'><b>3</b></div>5<br/>20"]
    end

    subgraph z[<div style='font-size:21px'><b>z</b><br/></div>]
        4.z["<div style='font-size:18px'><b>4</b></div>6<br/>30"]
    end

    15.A --> E17
    6.B --> 14.B
    14.B --> E16
    13.C --> 12.C
    12.C --> 8.C
    8.C --> 7.C
    7.C --> 9.C
    9.C --> E14
    6.D --> 8.D
    7.D --> 9.D
    8.D --> 7.D
    9.D --> E19
    10.E --> 11.E
    11.E --> E8
    10.F --> 11.F
    11.F --> E5
    13.G --> 12.G
    12.G --> 8.G
    8.G --> 7.G
    7.G --> 9.G
    9.G --> E11
    7.H --> 15.H
    15.H --> E26
    1.w --> E54
    2.x --> E55
    4.z --> E2
    3.y --> E56
    K43_1([<div style='font-size:10px'>K43</div>])
    K43_1 --- 15.A
    K44_1([<div style='font-size:10px'>K44</div>])
    K44_1 --- 15.A
    K44_2([<div style='font-size:10px'>K44</div>])
    K44_2 ---|2| 7.H
    K45_1([<div style='font-size:10px'>K45</div>])
    K45_1 --- 15.A
    K46_1([<div style='font-size:10px'>K46</div>])
    K46_1 --- 15.A
    E17 --> 3.y
    K28_1([<div style='font-size:10px'>K28</div>])
    K28_1 --- 6.B
    K28_2([<div style='font-size:10px'>K28</div>])
    K28_2 ---|4| 6.D
    K24_1([<div style='font-size:10px'>K24</div>])
    K24_1 --- 14.B
    K24_2([<div style='font-size:10px'>K24</div>])
    K24_2 ---|2| 1.w
    K24_3([<div style='font-size:10px'>K24</div>])
    K24_3 ---|2| 2.x
    K24_4([<div style='font-size:10px'>K24</div>])
    K24_4 --- 3.y
    K24_5([<div style='font-size:10px'>K24</div>])
    K24_5 --- 4.z
    K40_1([<div style='font-size:10px'>K40</div>])
    K40_1 --- 14.B
    K41_1([<div style='font-size:10px'>K41</div>])
    K41_1 --- 14.B
    K42_1([<div style='font-size:10px'>K42</div>])
    K42_1 ---|2| 14.B
    E16 --> 3.y
    K39_1([<div style='font-size:10px'>K39</div>])
    K39_1 --- 13.C
    K39_2([<div style='font-size:10px'>K39</div>])
    K39_2 --- 13.G
    K32_1([<div style='font-size:10px'>K32</div>])
    K32_1 --- 9.C
    K32_2([<div style='font-size:10px'>K32</div>])
    K32_2 --- 9.D
    K32_3([<div style='font-size:10px'>K32</div>])
    K32_3 --- 9.G
    E14 --> 1.w
    K59_1([<div style='font-size:10px'>K59</div>])
    K59_1 ---|2| 8.D
    E19 --> 1.w
    K57_1([<div style='font-size:10px'>K57</div>])
    K57_1 --- 10.E
    K57_2([<div style='font-size:10px'>K57</div>])
    K57_2 --- 10.F
    K58_1([<div style='font-size:10px'>K58</div>])
    K58_1 ---|36| 10.E
    K58_2([<div style='font-size:10px'>K58</div>])
    K58_2 ---|36| 10.F
    K35_1([<div style='font-size:10px'>K35</div>])
    K35_1 ---|2| 11.E
    K35_2([<div style='font-size:10px'>K35</div>])
    K35_2 ---|2| 11.F
    K37_1([<div style='font-size:10px'>K37</div>])
    K37_1 --- 11.E
    K38_1([<div style='font-size:10px'>K38</div>])
    K38_1 --- 11.E
    E8 --> 1.w
    K36_1([<div style='font-size:10px'>K36</div>])
    K36_1 --- 11.F
    E5 --> 2.x
    E11 --> 2.x
    K48_1([<div style='font-size:10px'>K48</div>])
    K48_1 ---|2| 7.H
    K47_1([<div style='font-size:10px'>K47</div>])
    K47_1 --- 15.H
    E26 --> 4.z
    K25_1([<div style='font-size:10px'>K25</div>])
    K25_1 ---|2| 1.w
    K25_2([<div style='font-size:10px'>K25</div>])
    K25_2 ---|2| 2.x
    K26_1([<div style='font-size:10px'>K26</div>])
    K26_1 ---|2| 1.w
    E54 --> 2.x
    E55 --> 3.y
    K27_1([<div style='font-size:10px'>K27</div>])
    K27_1 --- 3.y
    K27_2([<div style='font-size:10px'>K27</div>])
    K27_2 --- 4.z
    E56 --> 4.z
    K22_1([<div style='font-size:10px'>K22</div>])
    K22_1 --- 4.z