"""changed table name demand forecast

Revision ID: 3acac447370d
Revises: 25dffe600017
Create Date: 2025-03-26 19:45:33.693503

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3acac447370d'
down_revision: str | None = '25dffe600017'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'demand_forecast',
        sa.Column('period', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
        sa.PrimaryKeyConstraint('period', 'item_id')
        )
    op.drop_table('_demand_forecast')
    op.drop_constraint('fk_bought_item_item', 'bought_item', type_='foreignkey')
    op.drop_constraint('bought_item_item_id_fkey', 'bought_item', type_='foreignkey')
    op.create_foreign_key(None, 'bought_item', 'item', ['id'], ['id'], onupdate='CASCADE')
    op.drop_constraint('fk_item_graph_node', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'graph_node', ['id'], ['id'])
    op.drop_constraint('fk_item_graph_node', 'process', type_='foreignkey')
    op.create_foreign_key(None, 'process', 'graph_node', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('process_input_item_id_fkey', 'process_input', type_='foreignkey')
    op.create_foreign_key(None, 'process_input', 'item', ['item_id'], ['id'])
    op.drop_constraint('fk_produced_item_item', 'produced_item', type_='foreignkey')
    op.drop_constraint('produced_item_item_id_fkey', 'produced_item', type_='foreignkey')
    op.create_foreign_key(None, 'produced_item', 'item', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produced_item', type_='foreignkey')
    op.create_foreign_key(
        'produced_item_item_id_fkey',
        'produced_item',
        'item',
        ['id'],
        ['id'],
        onupdate='CASCADE',
        ondelete='CASCADE'
        )
    op.create_foreign_key('fk_produced_item_item', 'produced_item', 'item', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'process_input', type_='foreignkey')
    op.create_foreign_key(
        'process_input_item_id_fkey',
        'process_input',
        'item',
        ['item_id'],
        ['id'],
        onupdate='CASCADE',
        ondelete='CASCADE'
        )
    op.drop_constraint(None, 'process', type_='foreignkey')
    op.create_foreign_key('fk_item_graph_node', 'process', 'graph_node', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('fk_item_graph_node', 'item', 'graph_node', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bought_item', type_='foreignkey')
    op.create_foreign_key(
        'bought_item_item_id_fkey',
        'bought_item',
        'item',
        ['id'],
        ['id'],
        onupdate='CASCADE',
        ondelete='CASCADE'
        )
    op.create_foreign_key('fk_bought_item_item', 'bought_item', 'item', ['id'], ['id'], ondelete='CASCADE')
    op.create_table(
        '_demand_forecast',
        sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='_demand_forecast_item_id_fkey'),
        sa.PrimaryKeyConstraint('period', 'item_id', name='_demand_forecast_pkey')
        )
    op.drop_table('demand_forecast')
    # ### end Alembic commands ###
