"""added many tables for orders as well as peridical changing data

Revision ID: 4badac6dd55e
Revises: 3acac447370d
Create Date: 2025-03-29 15:42:41.719947

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4badac6dd55e'
down_revision: str | None = '3acac447370d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
            'duration',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('minutes', sa.Interval(), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'simulation_config',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('simulation_virtual_start', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'time_point',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('minutes', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'input_inventory',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('period_id', sa.Integer(), nullable=False),
            sa.Column('item_quantities', sa.JSON(), nullable=False),
            sa.Column('item_values', sa.JSON(), nullable=False),
            sa.ForeignKeyConstraint(['period_id'], ['time_point.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'ws_capa',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('shifts', sa.Integer(), nullable=False),
            sa.Column('overtime', sa.Integer(), nullable=False),
            sa.Column('workstation_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['workstation_id'], ['workstation.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'ws_use_info',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('workstation_id', sa.Integer(), nullable=False),
            sa.Column('setup_events', sa.Integer(), nullable=False),
            sa.Column('idletime', sa.Integer(), nullable=False),
            sa.Column('time_needed', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['workstation_id'], ['workstation.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'item_production',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('producing_item_id', sa.Integer(), nullable=False),
            sa.Column('quantity', sa.Integer(), nullable=False),
            sa.Column('est_finish_at_id', sa.Integer(), nullable=False),
            sa.Column('est_finish_stdv_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['est_finish_at_id'], ['time_point.id'], ),
            sa.ForeignKeyConstraint(['est_finish_stdv_id'], ['duration.id'], ),
            sa.ForeignKeyConstraint(['producing_item_id'], ['item.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'order',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('order_kind', sa.String(length=50), nullable=False),
            sa.Column('created_at_id', sa.Integer(), nullable=False),
            sa.Column('expected_execution_at_mean_id', sa.Integer(), nullable=False),
            sa.Column('expected_execution_at_stdv_id', sa.Integer(), nullable=False),
            sa.Column('was_executed', sa.Boolean(), nullable=False),
            sa.Column('offered_to_us', sa.Boolean(), nullable=False),
            sa.Column('offered_by_us', sa.Boolean(), nullable=False),
            sa.Column('item_id', sa.Integer(), nullable=False),
            sa.Column('amount_inv_change', sa.Integer(), nullable=False),
            sa.Column('cash_flow_per_item', sa.Integer(), nullable=False),
            sa.Column('penalty', sa.Integer(), nullable=False),
            sa.Column('creation_cost', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['created_at_id'], ['time_point.id'], ),
            sa.ForeignKeyConstraint(['expected_execution_at_mean_id'], ['time_point.id'], ),
            sa.ForeignKeyConstraint(['expected_execution_at_stdv_id'], ['duration.id'], ),
            sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'direct_order',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['id'], ['order.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'marketplace_buy',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['id'], ['order.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'marketplace_sell',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['id'], ['order.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'material_order',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['id'], ['order.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
            'normal_order',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['id'], ['order.id'], ),
            sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normal_order')
    op.drop_table('material_order')
    op.drop_table('marketplace_sell')
    op.drop_table('marketplace_buy')
    op.drop_table('direct_order')
    op.drop_table('order')
    op.drop_table('item_production')
    op.drop_table('ws_use_info')
    op.drop_table('ws_capa')
    op.drop_table('input_inventory')
    op.drop_table('time_point')
    op.drop_table('simulation_config')
    op.drop_table('duration')
    # ### end Alembic commands ###
