"""changed some table names

Revision ID: ac41bfee71ba
Revises: c5ee9a4a4401
Create Date: 2025-03-30 16:11:19.517928

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac41bfee71ba'
down_revision: Union[str, None] = 'c5ee9a4a4401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
            'inventory',
            sa.Column('period', sa.Integer(), nullable=False),
            sa.Column('item_id', sa.Integer(), nullable=False),
            sa.Column('quantity', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
            sa.PrimaryKeyConstraint('period', 'item_id')
    )
    op.drop_table('inventory_result')
    op.drop_column('item_production', 'est_finish_stdv_id')
    op.drop_column('item_production', 'est_finish_at_id')
    op.drop_column('order', 'expected_execution_at_mean_id')
    op.drop_column('order', 'expected_execution_at_stdv_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
            'order',
            sa.Column('expected_execution_at_stdv_id', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
            'order',
            sa.Column('expected_execution_at_mean_id', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column('item_production', sa.Column('est_finish_at_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item_production', sa.Column('est_finish_stdv_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table(
            'inventory_result',
            sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='inventory_result_item_id_fkey'),
            sa.PrimaryKeyConstraint('period', 'item_id', name='inventory_result_pkey')
    )
    op.drop_table('inventory')
    # ### end Alembic commands ###
