"""changed foreign keys and constraints

Revision ID: c6d99915b052
Revises: ac41bfee71ba
Create Date: 2025-04-04 17:25:07.064412

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6d99915b052'
down_revision: str | None = 'ac41bfee71ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ws_capa')
    op.drop_table('normal_order')
    op.drop_table('order')
    op.drop_table('direct_order')
    op.drop_table('item_production')
    op.drop_table('material_order')
    op.drop_table('ws_use_info')
    op.drop_constraint('bought_item_id_fkey', 'bought_item', type_='foreignkey')
    op.create_foreign_key(None, 'bought_item', 'item', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('inventory_item_id_fkey', 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'quantity')
    op.drop_column('inventory', 'item_id')
    op.drop_constraint('item_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'graph_node', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('item', 'type')
    op.add_column('process', sa.Column('process_duration_minutes', sa.Integer(), nullable=False))
    op.add_column('process', sa.Column('setup_duration_minutes', sa.Integer(), nullable=False))
    op.drop_column('process', 'process_duration')
    op.drop_column('process', 'setup_duration')
    op.drop_constraint('produced_item_id_fkey', 'produced_item', type_='foreignkey')
    op.create_foreign_key(None, 'produced_item', 'item', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produced_item', type_='foreignkey')
    op.create_foreign_key('produced_item_id_fkey', 'produced_item', 'item', ['id'], ['id'])
    op.add_column('process', sa.Column('setup_duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('process', sa.Column('process_duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('process', 'setup_duration_minutes')
    op.drop_column('process', 'process_duration_minutes')
    op.add_column('item', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_id_fkey', 'item', 'graph_node', ['id'], ['id'])
    op.add_column('inventory', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventory', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('inventory_item_id_fkey', 'inventory', 'item', ['item_id'], ['id'])
    op.drop_constraint(None, 'bought_item', type_='foreignkey')
    op.create_foreign_key('bought_item_id_fkey', 'bought_item', 'item', ['id'], ['id'], onupdate='CASCADE')
    op.create_table(
            'ws_use_info',
            sa.Column('workstation_id', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('setup_events', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('idletime', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('time_needed', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['workstation_id'], ['workstation.id'], name='ws_use_info_workstation_id_fkey')
    )
    op.create_table(
            'material_order',
            sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('order_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['id'], ['order.id'], name='material_order_id_fkey'),
            sa.PrimaryKeyConstraint('id', name='material_order_pkey')
    )
    op.create_table(
            'item_production',
            sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
            sa.Column('producing_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['producing_item_id'], ['item.id'], name='item_production_producing_item_id_fkey'),
            sa.PrimaryKeyConstraint('id', name='item_production_pkey')
    )
    op.create_table(
            'direct_order',
            sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('penalty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['id'], ['order.id'], name='direct_order_id_fkey'),
            sa.PrimaryKeyConstraint('id', name='direct_order_pkey')
    )
    op.create_table(
            'order',
            sa.Column(
                    'id',
                    sa.INTEGER(),
                    server_default=sa.text("nextval('order_id_seq'::regclass)"),
                    autoincrement=True,
                    nullable=False
            ),
            sa.Column('order_kind', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
            sa.Column('was_executed', sa.BOOLEAN(), autoincrement=False, nullable=False),
            sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('cash_flow_per_item', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='order_item_id_fkey'),
            sa.PrimaryKeyConstraint('id', name='order_pkey'),
            postgresql_ignore_search_path=False
    )
    op.create_table(
            'normal_order',
            sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['id'], ['order.id'], name='normal_order_id_fkey'),
            sa.PrimaryKeyConstraint('id', name='normal_order_pkey')
    )
    op.create_table(
            'ws_capa',
            sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
            sa.Column('shifts', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('overtime', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column('workstation_id', sa.INTEGER(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['workstation_id'], ['workstation.id'], name='ws_capa_workstation_id_fkey'),
            sa.PrimaryKeyConstraint('id', name='ws_capa_pkey')
    )
    # ### end Alembic commands ###
