@startuml

class Material{
    + id: int
    + value: int
}




class Process {
    + workstation: Workstation
    + setup_duration: Duration
    + run_duration: Duration
    + required_inputs: Map<Material, int>
    + output: Material
}

@enduml