@startuml
' ===== ORM Package =====
package Models {
  class MaterialGraphORM {
    + id: int
    + name: String
  }

  class Process {
    + id: int
    + duration: int
  }

  class ProcessIn {
    + quantity: int
  }

  class ProcessOut {
  }

  class Item {
    + id: int
  }
  class Bought extends Item{
  }

  class Workstation {
    + id: int
  }

  class TimeStamp {
    + day: int
    + hour: int
    + minute: int

    - calculate_period(): int
  }

  class Inventory{
    + id: int
    - timestamp: TimeStamp
  }

  ' ORM Associations
  MaterialGraphORM "0..1" o-- "n" Process
  MaterialGraphORM "0..1" o--- "n" MaterialGraphORM: "subgraph"
  Process "1" o-- "n" ProcessIn
  Process "1" o-- "1" ProcessOut
  ProcessIn o-- Item
  ProcessOut o-- Item
  ProcessORM "n" o-- "1" Workstation
}



package Material {

    class MaterialGraph {
        + id: int
        + name: String
        + processes: List<Process>
        + subgraphs: List<MaterialGraph>
    }


    class CalculateResourceRequirements {
        + calculate(graph: MaterialGraph): List[Workstation]
    }

}
package Conversion {
  class ProcessConverter {
  }

  class GraphConverter {
  }

  ' Dependencies
  GraphConverter ..> ProcessConverter
  GraphConverter ..> Material.MaterialGraph
  GraphConverter ..> Models.MaterialGraphORM
  ProcessConverter ..> Process
}




package "Visualization" {
    class VisualizationConverter {
      + convert(graph): MaterialGraph
    }
  interface MermaidContent {
    + get_mermaid_code() : String
  }

  class ClassDef implements MermaidContent {
    + fill: String
    + stroke: String
  }

  class MermaidStyle implements MermaidContent {
    + get_mermaid_code() : String
  }

  class MermaidBuilder implements MermaidContent {
    + addNode()
    + addRounded()
    + addArrow()
  }

  class VisualizeMermaid implements MermaidContent {
    - graph: MaterialGraph
    + get_mermaid_code() : String
  }

  ' Visualization Dependencies
  VisualizationConverter --> Material.MaterialGraph
  VisualizeMermaid --> MermaidBuilder
  VisualizeMermaid --> MaterialGraph
  VisualizeMermaid ..> Process
}

Material.MaterialGraph ... Models.MaterialGraphORM

@enduml
